name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1"

      - name: Build
        run: lua scripts/build.lua

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/resonance.lua
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}